# Generated by Django 6.0.2 on 2026-03-05 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_course_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='age_group',
            field=models.CharField(choices=[('minor', 'Minor'), ('adult', 'Adult')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=255, unique=True),
        ),
    ]
