services:
  backend:
    build:
      context: ./backend
      target: prod
    container_name: django_backend
    restart: always
    environment:
      LOAD_FIXTURE_ON_STARTUP: "1"
    volumes:
      - media_data:/app/media
    ports:
      - "8007:8000"

  frontend:
    build:
      context: ./frontend
      target: prod
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-https://haldaniko.com.ua}
    container_name: frontend_prod
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  media_data:
