services:
  backend:
    build:
      context: ./backend
      target: dev
    container_name: django_backend
    environment:
      LOAD_FIXTURE_ON_STARTUP: "1"
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      target: dev
    container_name: frontend_dev
    environment:
      NEXT_PUBLIC_API_URL: "http://localhost:8000"
      API_INTERNAL_URL: "http://backend:8000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend
